### PR TITLE
added checks for new IHT tab

### PR DESCRIPTION
**Pull request by AhsanZia-Moodys**
**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

### CODE REVIEW

**Review by Mitesh1909 — CHANGES_REQUESTED** [review]
Does this change not have to be on grantOfProbatePath.js too?

**Comment by AhsanZia-Moodys** [comment]
> Does this change not have to be on grantOfProbatePath.js too?

I have discovered that the IHT tab is added to the case once the expected estate page is complete. In the normal journey, the expected estate page doesn't get completed, therefore the IHT tab doesn't show up and is not needed in those files.

**Review by Mitesh1909 — COMMENTED** [review]
Would it not be better to use a EE application than a IHT207? This way we can check the Gross, Net and Net Qualifying text and values?

**Comment by AhsanZia-Moodys** [comment]
> Would it not be better to use a EE application than a IHT207? This way we can check the Gross, Net and Net Qualifying text and values?

Gross, Net and Net qualifying text has been checked in the "src/test/end-to-end/pages/caseDetails/grantOfProbate/ihtTabConfig.json" files. The IHT207 is selected in the EE Yes journey and checked in the tab to see if IHT207 is visible.

**Review by Mitesh1909 — APPROVED** [review]

**Pull request merged**
